### ISSUE TITLE
no class member rule fails in standard angular modules

### ISSUE THREAD

**Issue by realshaft** [ng-seed/angular-tslint-rules#13]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
After running tslint with angular-tslint-rules I do get
```This class has no members.```

**Expected/desired behavior**
This Error should not occur as it is a standard angular design to export classes in modules without 'member'

**Minimal reproduction of the problem with instructions**
Simply run lint with the rules over a new project, normally the app.module.ts looks like
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
  ],
  exports: [],
  providers: [
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**What is the motivation / use case for changing the behavior?**
This rules should be disabled or rewritten? Not sure here. Which rule is that?

**Environment**
* **Angular version:** 5.0.3

* **Browser:**
- [x ] Chrome (desktop) version 62
- [ x] Firefox version 57
- [ x] Safari (desktop) version High Sierra

* **For Tooling issues:**
- Node version: XX  
- Platform:  Mac High Sierra

* Others:
angular-cli, IntelliJ

**Comment by Koslun** [comment]
It's [this rule](https://palantir.github.io/tslint/rules/no-unnecessary-class/), specifically it's been configured like this: 
```
"no-unnecessary-class": [
  true,
  "allow-constructor-only",
  "allow-static-only"
]
```

Your example would be solved by adding option `"allow-empty-class"` to this rule.

That particular example would be solved by adding:
`https://palantir.github.io/tslint/rules/no-unnecessary-class/`

**Comment by realshaft** [comment]
Thank you for your help. I will close this issue.

Because it is very common in an angular project to have those classes, I would suggest to make that ```"allow-empty-class"```default

**Comment by Koslun** [comment]
@realshaft agree on that change. So think it would make sense to re-open this until it's fixed in this project.
