### ISSUE TITLE
no-implicit-dependencies should be [true, "dev"]

### ISSUE THREAD

**Issue by realshaft** [ng-seed/angular-tslint-rules#14]
**I'm submitting a ...**  (check one with "x")
```
[x] Feature request
```

**Current behavior**
The lint rule [no-implicit-depencies](https://palantir.github.io/tslint/rules/no-implicit-dependencies/ ) has it's setting to ```true```

**Expected/desired behavior**
It should be ```[true, "dev"]```

**Minimal reproduction of the problem with instructions**
angular-cli create a project, install angular tslint rules and run.

**What is the motivation / use case for changing the behavior?**
angular or angular-cli usually uses dependencies and devDependencies in package.json. If you run tslint over the whole code including for example e2e test cases and test configuration it will fail if packages are imported only under devDependencies. 
```e2e/app.po.ts[1, 38]: Module 'protractor' is not listed as dependency in package.json```

**Environment**
* **Angular version:** 5.0.4

* **For Tooling issues:**
- Node version: 8.9.1
- Platform:  Mac

**Comment by fulls1z3** [comment]
@realshaft this is a very generic rule, and can depend project-to-project. the best solution is to override this rule at your local tslint.json
