### ISSUE TITLE
explain `curly as-needed` rule

### ISSUE THREAD

**Issue by bjorkegeek** [ng-seed/angular-tslint-rules#19]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
```

**Current behavior**
The "curly" rule currently specifies the "as-needed" behavior which goes against most coding standards including [Google Javascript guide](https://google.github.io/styleguide/jsguide.html#formatting-braces-all) and [Typescript Guidelines](https://github.com/unional/typescript-guidelines/blob/HEAD/pages/default/draft/blocks.md). A rationale explaining this behavior would be be useful.

**Expected/desired behavior**
That the documentation contains an explanation (or a link to an explanation) of why this rule makes sense in the context of angular development.

**Minimal reproduction of the problem with instructions**
1. Read angular-tslint-rules documentation
2. Google "tslint curly as-needed reason"
3. Go through commit messages in tslint to try to find a reason for the "as-needed" option to exist
4. Give up attempts to understand. 

**What is the motivation / use case for changing the behavior?**
Agreeing with a motivation for a coding style rule is not necessary to apply it, but applying it without understanding the underlying the motivation might result in writing code that only follows the letter but not the spirit of the coding style.

**Comment by fulls1z3** [comment]
available as of v1.12.1
