### ISSUE TITLE
Support Codelyzer 5

### ISSUE THREAD

**Issue by TheAifam5** [ng-seed/angular-tslint-rules#36]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Current behavior**
```
warning " > angular-tslint-rules@1.14.0" has incorrect peer dependency "codelyzer@>=4.5.0 <5.0.0".
```

**Expected/desired behavior**
No warning.

**What is the motivation / use case for changing the behavior?**
Warningless :)

**Other**
What was the reason to remove support for 5.0.0?

**Comment by fulls1z3** [comment]
@TheAifam5 that's all about public API change in codelyzer.

Please see https://github.com/mgechev/codelyzer/blob/master/CHANGELOG.md

**Comment by AdaskoTheBeAsT** [comment]
@fulls1z3 could you please shed more light on this?
This is connected only with changing names of rules or there is something more fundamental.
I am just curious - if only naming then of course community can help with that but if there is something more fundamental then indeed it can be more challenging

**Comment by thetric** [comment]
@AdaskoTheBeAsT @TheAifam5 see my PR #37

**Comment by TheAifam5** [comment]
Something went wrong :)
```
[error] FatalError: Failed to load src/tslint.json: Unexpected string in JSON at position 3852 in node_modules/angular-tslint-rules/tslint.json
    at new FatalError (node_modules/tslint/lib/error.js:27:28)
    at Object.findConfiguration (node_modules/tslint/lib/configuration.js:57:15)
    at _lint (node_modules/@angular-devkit/build-angular/src/tslint/index.js:137:40)
    at _run (node_modules/@angular-devkit/build-angular/src/tslint/index.js:57:35)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
```

**Comment by fulls1z3** [comment]
@TheAifam5 known issue, bumped version after version to match tslint@5.18.0

use v1.18.0 and it works
